/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    ArticleContent: typeof import('./src/components/ArticleContent.vue')['default']
    ArticleHeader: typeof import('./src/components/ArticleHeader.vue')['default']
    ArticleNavigation: typeof import('./src/components/ArticleNavigation.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    BackToList: typeof import('./src/components/BackToList.vue')['default']
    BlogPostCard: typeof import('./src/components/BlogPostCard.vue')['default']
    CommentCard: typeof import('./src/components/CommentCard.vue')['default']
    CommentForm: typeof import('./src/components/CommentForm.vue')['default']
    CommentList: typeof import('./src/components/CommentList.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    GlobalLoading: typeof import('./src/components/GlobalLoading.vue')['default']
    HomeSelf: typeof import('./src/components/HomeSelf.vue')['default']
    LearningPlanCard: typeof import('./src/components/LearningPlanCard.vue')['default']
    LoginDialog: typeof import('./src/components/LoginDialog.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    ProjectCard: typeof import('./src/components/ProjectCard.vue')['default']
    ProjectModal: typeof import('./src/components/ProjectModal.vue')['default']
    ReadingProgressBar: typeof import('./src/components/ReadingProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SEOStatus: typeof import('./src/components/SEOStatus.vue')['default']
    ShareButtons: typeof import('./src/components/ShareButtons.vue')['default']
    SkillProgressBar: typeof import('./src/components/SkillProgressBar.vue')['default']
    SocialLinks: typeof import('./src/components/SocialLinks.vue')['default']
    TableOfContents: typeof import('./src/components/TableOfContents.vue')['default']
    TechBadge: typeof import('./src/components/TechBadge.vue')['default']
    TechCloud: typeof import('./src/components/TechCloud.vue')['default']
    Timeline: typeof import('primevue/timeline')['default']
    Toast: typeof import('primevue/toast')['default']
    TypeWriter: typeof import('./src/components/TypeWriter.vue')['default']
    UserMenu: typeof import('./src/components/UserMenu.vue')['default']
    WaveBackground: typeof import('./src/components/WaveBackground.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
